condense_wildcard_suffixes = true
edition                    = "2021"

# Unstable features below
# fn_args_layout               = "Vertical"
fn_single_line               = true
format_code_in_doc_comments  = true
format_macro_matchers        = true
format_strings               = true
group_imports                = "StdExternalCrate"
imports_granularity          = "Module"
imports_indent               = "Visual"
imports_layout               = "Horizontal"
# indent_style                 = "Visual"
max_width                    = 120
newline_style                = "Unix"
normalize_comments           = true
normalize_doc_attributes     = true
reorder_impl_items           = true
struct_field_align_threshold = 90
unstable_features            = true
use_field_init_shorthand     = true
use_try_shorthand            = true
# wrap_comments                = true
